# Screen Size
WIDTH = 600
HEIGHT = 600

ROWS = 3
COLUMNS = 3
SQUARE_SIZE = WIDTH // COLUMNS

MEDIUM_ROWS = 4
MEDIUM_COLUMNS = 4
MEDIUM_SQUARE_SIZE = WIDTH // MEDIUM_COLUMNS

LARGE_ROWS = 5
LARGE_COLUMNS = 5
LARGE_SQUARE_SIZE = WIDTH // LARGE_COLUMNS

LINE_WIDTH = 15

# Colours
BACKGROUND_COLOUR = (224, 255, 255)
LINE_COLOUR = (104, 131, 139)
